name: Run Python Miner Test
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Lets you trigger it manually

jobs:
  run-miner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - run: python cli.py --mode interactive --wallet 1HwQuxoGiUciUKE99NDJifNBpRp63er4Nw